ams/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import home

urlpatterns = [
    # Examples:
    # url(r'^$', 'ams.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', home, name='home'),
    url(r'^attendance/', include('attendance.urls', namespace='attendance')),
    url(r'^account/', include('account.urls', namespace='account')),
]

attendance/urls.py
from attendance import views
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.preview_excel, name='upload'),
    url(r'^submit/$', views.submit, name='submit'),
    url(r'^login/$', auth_views.login, name="login"),
    url(r'^logout/$', auth_views.logout, name="logout"),
]

attendance/models.py
import datetime

from django.contrib.auth.models import Group
from django.db import models


class Person(models.Model):
    """
    an abstract base class (model) for holding attributes that are common to other
    models. This model is ignored during migrations, thus doesn't translate into an
    actual database table
    """
    full_name = models.CharField(max_length=150)
    gender = models.CharField(max_length=7, blank=True, null=True, choices=(('M', 'Male'), ('F', 'Female')))

    class Meta:
        abstract = True


# class AttendanceStatus(models.Model):
#     """
#     various attendance status that can be attributed to a student
#     """
#     name = models.CharField(max_length=255, unique=True,
#                             help_text='"Present" will not be saved but will show as a teacher option.')
#     code = models.CharField(max_length=10, unique=True,
#                             help_text="Short code used on attendance reports. Ex: A might be the code for the "
#                                       "name Absent")
#
#     class Meta:
#         verbose_name_plural = 'Attendance Statuses'
#
#     def __str__(self):
#         return self.name
#

class Instructor(Person):
    email = models.EmailField(blank=True, null=True)

    class Meta:
        ordering = ("full_name",)

    def save(self, make_user_group=True, *args, **kwargs):
        self.is_staff = True
        super(Instructor, self).save(*args, **kwargs)
        if make_user_group:
            group, created = Group.objects.get_or_create(name="Faculty")
            # self.groups.add(group)

    def __str__(self):
        return "{}".format(self.full_name)


class Student(Person):
    email = models.EmailField()
    student_id = models.CharField(max_length=10, unique=True)

    class Meta:
        ordering = ("full_name",)

    def save(self, make_user_group=True, *args, **kwargs):
        self.is_staff = True
        super(Student, self).save(*args, **kwargs)
        if make_user_group:
            group, created = Group.objects.get_or_create(name="Student")
            # self.groups.add(group)

    def __str__(self):
        return "{}".format(self.full_name)


class Course(models.Model):
    # is_active = models.BooleanField(default=True)
    code = models.CharField(max_length=7, unique=True, verbose_name='Course Code')
    title = models.CharField(max_length=255, unique=True, verbose_name="Course Title")
    description = models.TextField(blank=True)

    def __str__(self):
        return self.code


class CourseSection(models.Model):
    course = models.ForeignKey(Course, related_name='sections')
    # is_active = models.BooleanField(default=True)
    section_number = models.PositiveSmallIntegerField()
    instructors = models.ManyToManyField(Instructor, blank=True)
    enrollment = models.ManyToManyField(Student, blank=True)

    def __str__(self):
        return '{} section {}'.format(self.course, self.section_number)


class CourseSectionAttendance(models.Model):
    """
        Attendance taken at each course (section)
    """
    STATUSES = (
        ('A', 'Absent'),
        ('L', 'Late'),
        ('X', 'Present'),
    )
    student = models.ForeignKey(Student)
    course_section = models.ForeignKey(CourseSection)
    date = models.DateTimeField()
    time_in = models.TimeField(blank=True, null=True)
    status = models.CharField(max_length=50, blank=True, null=True, choices=STATUSES)
    notes = models.CharField(max_length=500, blank=True, null=True)

    def __str__(self):
        return '{} {} {}'.format(self.student, self.date, self.status)

attendance/forms.py
import os
from django import forms

IMPORT_FILE_TYPES = ['.xls', '.xlsx']


class AttendanceImportForm(forms.Form):
    input_excel = forms.FileField(required=True, label="Upload Excel file.")

    def clean_input_excel(self):
        input_excel = self.cleaned_data['input_excel']
        extension = os.path.splitext(input_excel.name)[1]
        if not (extension in IMPORT_FILE_TYPES):
            raise forms.ValidationError(
                '{} is not a valid excel file. Please make sure your input file is an excel file'.format(extension))
        else:
            return input_excel


class AttendanceSubmitForm(forms.Form):
    pass

attendance/views.py
import os

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.shortcuts import render

from attendance.models import CourseSection, Course, Student, Instructor, CourseSectionAttendance
from .attendance import Attendance
from .forms import AttendanceImportForm

@login_required(login_url='admin:login')
def preview_excel(request):
    if request.method == 'POST':
        form = AttendanceImportForm(request.POST, request.FILES)
        if form.is_valid():
            file_obj = request.FILES['input_excel']
            path = default_storage.save('tmp/' + str(file_obj), ContentFile(file_obj.read()))
            tmp_file_path = os.path.join(settings.MEDIA_ROOT, path)  # temporarily store excel file on disk

            attendance_sheet = Attendance.get_sheet(tmp_file_path)  # read the file from the remp folder
            attendance_json = Attendance.get_attendance_json(Attendance(), attendance_sheet)
            request.session[
                'get_data'] = attendance_json  # store all the attendance data on a session to be used in another view
            os.remove(tmp_file_path)  # delete the file from the temp folder to free up memory
            return render(request, 'attendance/confirm_file.html', {'attendance_json': attendance_json})
    else:
        form = AttendanceImportForm()
    return render(request, 'attendance/upload.html', {'form': form})

@login_required(login_url='admin:login')
def submit(request):
    # if request.method == 'POST':
    if request.session.get('get_data') is not None:
        attendance_data = request.session.get('get_data')
        course_code = attendance_data['data']['course']['code']
        description = attendance_data['data']['course']['description']
        section = attendance_data['data']['course']['section']
        instructor = attendance_data['data']['course']['instructor']
        instructor, created = Instructor.objects.get_or_create(full_name=instructor)
        course, created = Course.objects.get_or_create(code=course_code, title=description, )
        course_section, created = CourseSection.objects.get_or_create(course=course, section_number=section)
        course_section.instructors.add(instructor)
        for student in attendance_data['data']['attendances']:
            student_id = student['student_aun_id']
            email = student['email']
            full_name = student['names']
            new_student, created = Student.objects.get_or_create(student_id=student_id, email=email,
                                                                 full_name=full_name)
            course_section.enrollment.add(new_student)

            for status in student['statuses']:
                date = status['date']
                att_status = status['status']
                CourseSectionAttendance.objects.get_or_create(student=new_student, course_section=course_section, date=date, status=att_status)
        return render(request, 'attendance/thanks.html', {'thanks': 'Thanks'})
    else:
        form = AttendanceImportForm()
    return render(request, 'attendance/upload.html', {'form': form})

    # else:
    #     form = AttendanceImportForm()
    # return render(request, 'attendance/upload.html', {'form': form})

attendance/templates/attendance/confirm_file.html
{#{% extends "base.html" %}#}
{% load static %}

{% block title %}
    {#    Confirm attendance#}
{% endblock %}

{% block content %}
    {#    {{ attendance_json }}#}
    <p><strong>Instructor: </strong> {{ attendance_json.data.course.instructor }}</p>
    <p><strong>Course Code: </strong>{{ attendance_json.data.course.code }}</p>
    <p><strong>Course Title: </strong>{{ attendance_json.data.course.description }}</p>
    <p><strong>Course Section: </strong>{{ attendance_json.data.course.section }}</p>
    <table border="1" layout-padding="5" cellpadding="5">
        <tr>
            <th>Student ID</th>
            <th>Student Names</th>
            <th>Student Email</th>
            {% for date in attendance_json.data.attendances.0.statuses %}
                <th style="font-size: xx-small;">{{ date.date }}</th>
            {% endfor %}
        </tr>
        {% for item in attendance_json.data.attendances %}
            <tr>
                <td>{{ item.student_aun_id }}</td>
                <td>{{ item.names }}</td>
                <td>{{ item.email }}</td>
                {% for status in item.statuses %}
                    <td>{{ status.status }}</td>
                {% endfor %}
            </tr>
        {% endfor %}
    </table>
{#    <form action="submit/" method="POST" enctype="multipart/form-data">#}
{#        {% csrf_token %}#}
{#        {{ form }}#}
{#        <input type="hidden" name="file" value="{{ file }}">#}
{#        <input type="submit" class="submit_btn btn label-success" value="Submit"/>#}
{#    </form>#}
    <td><a href="{% url "attendance:submit" %}">Submit</a></td>
    <td><a href="{% url "attendance:upload" %}">cancel</a></td>

{% endblock %}

attendance/templates/attendance/thanks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Feedback</h2>
<hr>
{{ thanks }}
<br>
<a href="{% url "attendance:upload" %}">Back</a>

</body>
</html>

attendance/templates/attendance/upload.html
{#{% extends "base.html" %}#}
{% load static %}

{% block title %}
    {#    Upload attendance#}
{% endblock %}

{% block content %}
{#    {% if thanks %}{{ thanks }}{% endif %}#}
    {{ thanks }}
    <form action="." method="POST" enctype="multipart/form-data" >
        {% csrf_token %}
        {{ form }}
        <p><input type="submit" value="Upload Attendance"></p>
    </form>
{% endblock %}